FILENAME: 18549vis_utils.py, LINE: 188 (Empty exception detected)
FILENAME: 14179babi_memnn.py, LINE: 101 (Too general exception)
FILENAME: 15172resnet_v2.py, LINE: 7 (Too general exception)
FILENAME: 11657cntk_backend.py, LINE: 2612 (Too general exception)
FILENAME: 14141test_utils.py, LINE: 23 (Too general exception)
FILENAME: 43171babi_rnn.py, LINE: 162 (Too general exception)
FILENAME: 10498test_callbacks.py, LINE: 28 (Too general exception)
FILENAME: 5463resnext.py, LINE: 7 (Too general exception)
FILENAME: 8266resnet.py, LINE: 7 (Too general exception)
FILENAME: 4194test_model_saving.py, LINE: 26 (Too general exception)
FILENAME: 173124io_utils_test.py, LINE: 25 (Too general exception)
